Backend: Vivado
Board: null
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 64
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'vgg16/keras_model.h5'
OutputDir: vgg16
OutputPredictions: null
ProjectName: myproject
Stamp: 00FcDA4f
XilinxPart: xczu9eg-ffvb1156-2-e
